###################################
##  Notifies me via IFTTT when something goes down.
###################################

- alias: 'Device Status'
  hide_entity: True
  trigger:
       - platform: state
         entity_id: 
           - sensor.wii
           - sensor.hue_hub
           - sensor.tablotv
           - sensor.alexa_echo
           - sensor.amazon_dot
           - sensor.circle
           - sensor.rachio
           - sensor.skybell
           #- sensor.samsungtv
           - sensor.chromecast_audio_1
           - sensor.chromecast_audio_2
           - sensor.nest_upstairs
           - sensor.nest_downstairs
           - sensor.cisco_ap
           - sensor.actiontechap
           - sensor.small_garage
           - sensor.large_garage
           - sensor.led_rgb_garage_left
           - sensor.led_rgb_garage_small
           - sensor.led_rgb_outdoor_den
           #- sensor.withings_scale
           - sensor.smart_water_meter
           - sensor.sleep_number_bed
           
  action:
    - service: script.ifttt_notify
      data_template:
        value1: 'Device Status:'
        value2: "{{ trigger.entity_id.split('.')[1]|replace('_', ' ') }} is "
        value3: "{{ trigger.to_state.state }}"
      
    - service: script.Voice_notify
      data_template:
        value1: "{{ trigger.entity_id.split('.')[1]|replace('_', ' ') }} is now {{ trigger.to_state.state }}"
        
