##############################################################################
###  Detect when things are on and forgotten about. Like any Good Watchdog.
##############################################################################
        
- alias: "Disk Use Alarm"
  trigger:
    - platform: numeric_state
      entity_id: sensor.disk_use_
      above: 80
  action:
    - service: script.Voice_notify
      data_template:
        value1: 'ATTENTION: Your harddrive is running out of Space! /dev/root:{{ states.sensor.disk_use_.state }}%!'
    - service: script.ifttt_notify
      data_template:
        value1: 'Hard Drive Monitor:'
        value2: "Your harddrive is running out of Space! /dev/root:{{ states.sensor.disk_use_.state }}%!"
        value3: ' '
    - service: persistent_notification.create
      data:
        title: "Hard Drive Monitor:"
        message: "Your harddrive is running out of Space! /dev/root:{{ states.sensor.disk_use_.state }}%!"
        notification_id: "Critical Alert"
