###################################
##  Uses IFTTT to trigger rain delay with rachio
###################################

- alias: Rachio_Rain_Delay
  hide_entity: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_precip_intensity_max
      above: 0.5

  action:
    - service: ifttt.trigger
      data_template: {"event":"Rachio_Rain_Delay"}
