homeassistant:
  name: Bear Stone Run 
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize  

http:
  api_password: !secret http_api_password
  
frontend:
group: !include_dir_merge_named group
device_tracker: !include_dir_merge_list device_tracker
discovery:
updater:
sun:

light:
  platform: hue
  host: 192.168.10.106
  allow_unreachable: true

ifttt:
  key: !secret ifttt_key

# history:

logbook:
  exclude:
    entities:
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
#logger:
#  default: info
recorder:
  purge_days: 14

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: pi
  password: raspberry
  
zwave:
 usb_path: /dev/ttyACM0
 config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

nest:
  username: !secret nest_username
  password: !secret nest_password
  
climate:
  platform: nest

media_player:
  platform: cast
   
sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
switch: !include_dir_merge_list switch
