homeassistant:
  name: Bear Stone Run
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize

http:
  base_url: !secret http_base_url
  api_password: !secret http_api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  trusted_networks:
    - 192.168.10.0/24
    - 127.0.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 3

frontend:

group: !include_dir_merge_named group
device_tracker: !include_dir_merge_list device_tracker
#discovery:
updater:
sun:

light:
  - platform: hue
    host: 192.168.10.75
    filename: phue.conf
    allow_unreachable: true
    allow_in_emulated_hue: false
    allow_hue_groups: false

light 2:
  - platform: hue
    host: 192.168.10.76
    filename: phue2.conf
    allow_unreachable: true
    allow_in_emulated_hue: false
    allow_hue_groups: false

# Reference : https://www.flexfireleds.com/pages/Comparison-between-3528-LEDs-and-5050-LEDs.html
  - platform: flux_led
    automatic_add: True
    devices:
      192.168.10.213:
        name: garage_large
        mode: "rgb"

emulated_hue:
  host_ip: 192.168.10.10
  listen_port: 8300
  expose_by_default: false

ifttt:
  key: !secret ifttt_key

logbook:
  exclude:
    entities:
      - automation.detect_lights_and_adjust_the_brightness_when_turned_on_based_on_time
      - automation.cuckoo_clock
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.small_garage_status
      - sensor.large_garage_status
      - sensor.small_garage_time_in_state
      - sensor.large_garage_time_in_state
      - sensor.large_garage_wifi_signal_strength
      - sensor.small_garage_wifi_signal_strength
      - sensor.small_garage_reflection_rate
      - sensor.large_garage_reflection_rate
      - group.garage_doors
      - sensor.time
      - sensor.date
      - media_player.LivingRoomCC


history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
  exclude:
    entities:
     - sensor.last_boot
     - sensor.date

logger: !include logger.yaml
recorder: !include recorder.yaml

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-Carlo
  username: !secret MQTT_username
  password: !secret MQTT_password

zwave:
 usb_path: /dev/zwave
 config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

climate:
  platform: nest

media_player:
  - platform: cast
  - platform: roku


sleepiq:
  username: !secret sleepiq_username
  password: !secret sleepiq_password

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_ID
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: 'us-east-1'

cover:
  platform: garadget
  covers:
      !secret large_garage_id:
        username: !secret garadget_username
        password: !secret garadget_password
        name: Large Garage
      !secret small_garage_id:
        username: !secret garadget_username
        password: !secret garadget_password
        name: Small Garage

sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
switch: !include_dir_merge_list switch
script: !include_dir_merge_named script
input_boolean: !include_dir_merge_named input_boolean
shell_command: !include_dir_merge_named shell_command
