#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------
homeassistant:
  customize:
    input_boolean.lastmsg:
      friendly_name: 'Repeat Message'
      icon: mdi:repeat-once
      emulated_hue: True
      hidden: False
#-------------------------------------------
input_boolean:
  lastmsg:
    name: Last Message
    initial: off
#-------------------------------------------
sensor:
  - platform: mqtt
    state_topic: "polly/lastmsg"
    name: "Last Message"
##############################################################################
###  Automations - Detect when things are not right. Like any Good Watchdog.
##############################################################################

automation:
  - alias: 'Repeat Last Message'

    trigger:
      - platform: state
        entity_id: input_boolean.lastmsg
        state: 'on'
        from: 'off'

    action:
      - service: script.speech_engine
