- platform: rpi_rf
  gpio: 17
  switches:
    Outlet_Living_Room:
      protocol: 1
      pulselength: 186
      code_on: 5265155
      code_off: 5265164
    Outlet_2:
      protocol: 1
      pulselength: 186
      code_on: 5264835
      code_off: 5264844
    Outlet_Garage:
      protocol: 1
      pulselength: 186
      code_on: 5264691
      code_off: 5264700 