- platform: rpi_rf
  gpio: 17
  switches:
# Outlet 1
    Living_Room_Amp:
      protocol: 1
      pulselength: 186
      code_on: 5265155
      code_off: 5265164
# Outlet 2
    Bathroom_Amp:
      protocol: 1
      pulselength: 186
      code_on: 5264835
      code_off: 5264844
# Outlet 3
    Garage_Outlet:
      protocol: 1
      pulselength: 186
      code_on: 5264691
      code_off: 5264700 