######################################################################
##  Announce when people come or go.
## Announce over all Chromecast Audios 
######################################################################
- alias: 'State Announcements'
  
  trigger:
    - platform: state
      entity_id:
        - device_tracker.carlo
        - device_tracker.stacey
        - device_tracker.franco
        - device_tracker.yolanda
        - device_tracker.joyce_ipad
      from: 'not_home'
      to: 'home'
      for: '00:02:00'
      
    - platform: state
      entity_id:
        - cover.garadget_large
        - cover.garadget_small
      from: 'closed'
      to: 'open'
      for: '00:02:00'
      
  action:
    - service: script.Voice_notify
      data_template:
        value1: "{{ trigger.entity_id.split('.')[1]|replace('_', ' ')|replace('garadget large', 'The large garage ')|replace('garadget small', 'The small garage ') }} is {{ (trigger.to_state.state)|replace('_', ' ') }}."