######################################################################
##  Announce when people come or go.
## Announce over all Chromecast Audios 
######################################################################
- alias: 'People Greeting'
  
  trigger:
    - platform: state
      entity_id:
        - device_tracker.carlo
        - device_tracker.stacey
        - device_tracker.franco
        - device_tracker.yolanda
        - device_tracker.joyce_ipad
      from: 'not_home'
      to: 'home'
      for: '00:02:00'
      
  action:
    - service: script.Voice_notify
      data_template:
        value1: >
          {{ [
          "Welcome home  {%trigger.entity_id.split('.')[1]|replace('_', ' ')%}",
          "Guess who is home?  {{ trigger.entity_id.split('.')[1]|replace('_', ' ')}} is!",
          "Attention:  {{trigger.entity_id.split('.')[1]|replace('_', ' ')}} is now in the house.",
          "{{ trigger.entity_id.split('.')[1]|replace('_', ' ')}} in da house!",
          "Welcome Home {{ trigger.entity_id.split('.')[1]|replace('_', ' ')}}.  We've missed you. or at least Molly did.",
          "Our home is now complete, Rest your head and relax your feet! Welcome Back {{ trigger.entity_id.split('.')[1]|replace('_', ' ')}}",
          "Life is like a song, you’re back where you belong. Welcome home {{ trigger.entity_id.split('.')[1]|replace('_', ' ')}}"
          ] | random }}      
    