######################################################################
##  Announce when people come or go.
## Announce over all Chromecast Audios 
######################################################################
- alias: 'People Greeting'
  
  trigger:
    - platform: state
      entity_id:
        - device_tracker.carlo
        - device_tracker.stacey
        - device_tracker.franco
        - device_tracker.yolanda
        - device_tracker.joyce_ipad
      from: 'not_home'
      to: 'home'
      for: '00:02:00'
      
  action:
    - service: script.Voice_notify
      data_template:
        value1: "{{ trigger.entity_id.split('.')[1]|replace('_', ' ')}} is {{ (trigger.to_state.state)|replace('_', ' ') }}."