######################################################################
##  Some home facts when we get back home from being away.
######################################################################
- alias: 'chores'

  trigger:

    - platform: state
      entity_id: input_boolean.chore_schedule
      state: 'on'
      from: 'off'

  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.chore_schedule

    - service: script.Voice_notify
      data_template:
        value1: >
          "{% if now().strftime("%j")|int % 2 == 0 %}
          Today is Justin's day to do chores.
          {% else %}
          Today is Paige's day to do chores.
          {%endif%}"
