- alias: Announce package delivery
  trigger:
    platform: state
    entity_id: sensor.deliveries_today

  condition:
    - condition: template
      value_template: '{{trigger.to_state.state|int > trigger.from_state.state|int}}'

  action:
    - service: script.Voice_notify
      data_template:
        value1: "A package was just delivered."
