######################################################################
##  Garage Status Announcements
######################################################################
- alias: 'Door Opened/Closed'

  trigger:
    - platform: state
      entity_id:
        - sensor.backdoor

  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.alert_mode

    - service: script.Voice_notify
      data_template:
        value1: "The {{ trigger.entity_id.split('.')[1]|replace('_', ' ') }} is now {{ (trigger.to_state.state)|replace('_', ' ') }}."
