###################################
## Garadget Stuff -  [Garadget](http://amzn.to/2jQLpVQ) - Garage Door opener/sensor
###################################

- alias: 'Wind Speed Garage Door Check'
  hide_entity: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_wind_speed
      above: 25

  condition:
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ states('cover.large_garage') == 'opened' }}"
        - condition: template
          value_template: "{{ states('cover.small_garage') == 'opened'}}"

  action:
    - service: script.ifttt_notify
      data_template:
        value1: 'Check Garage Doors:'
        value2: "Small: {{ states('cover.small_garage')}}"
        value3: "Large: {{ states('cover.large_garage')}}"

    - service: input_boolean.turn_on
      entity_id: input_boolean.alert_mode

    - service: script.Voice_notify
      data_template:
        value1: "Please check the garage doors. The Small garage is {{ states('cover.small_garage')}} and the large garage is {{ states('cover.large_garage')}}"
