###################################
## Tornados are no Joke.
###################################

- alias: 'High Wind Speed Notification'
  hide_entity: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_wind_speed
      above: 50

  action:
    - service: script.ifttt_notify
      data_template:
        value1: 'VERY HIGH WINDS:'
        value2: "{{ states('sensor.dark_sky_wind_speed')}}"
        value3: ' '

    - service: light.turn_on
      entity_id:
        - group.all_lights
      data:
        flash: short

    - service: input_boolean.turn_on
      entity_id: input_boolean.alert_mode

    - service: script.Voice_notify
      data_template:
        value1: >
          "ATTENTION: The wind speed is now {{ states('sensor.dark_sky_wind_speed')|round}} miles per hour.  Please make sure everyone is inside for safety."

    - service: light.turn_on
      entity_id:
        - group.all_lights
      data:
        flash: long
