######################################################################
##  Some home facts when we get back home from being away.
######################################################################
- alias: 'Home Stats'

  trigger:
    - platform: state
      entity_id:
        - group.family
      from: 'not_home'
      to: 'home'
      for: '00:03:00'

    - platform: state
      entity_id: input_boolean.home_stats
      state: 'on'
      from: 'off'

  action:
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.lights_status

    - service: script.Voice_notify
      data:
        call_inside_weather: 1
        call_responsibilities: 1
        call_outside_weather: 1
        call_garage_check: 1
