######################################################################
##  Who's day is it anyway? Pretty sure my parent's didn't code to figure this out.
######################################################################
- alias: 'responsibilities'

  trigger:

    - platform: state
      entity_id: input_boolean.responsibilities
      state: 'on'
      from: 'off'

  action:
    - service: script.Voice_notify
