######################################################################
##  What did she say? REPEAT THE LAST MESSAGE.
######################################################################
- alias: 'tts_repeat'
  
  trigger:
    - platform: state
      entity_id: input_boolean.last_message
      state: 'on'
      from: 'off'
      
  action:
    - service: script.Voice_notify
      data_template:
        value1: "{{states('sensor.polly_lastmsg')}}"