###################################################
## * Special HASS related sensors - Thanks @torn8o
###################################################

- platform: command_line
  name: HA Installed Version
  command: "/srv/hass/hass_venv/bin/hass --version"
  scan_interval: 86400

- platform: template
  sensors:
    ha_uptime:
      value_template: '{{ relative_time(states.automation.startup_notification.attributes.last_triggered) }}'
      friendly_name: HA Uptime
