###################################################
## Various MQTT sensors
###################################################

- platform: mqtt
  state_topic: "polly/lastmsg"
  name: "polly_lastmsg"
