###################################################
## Various MQTT sensors
###################################################

- platform: mqtt
  name: "Latest Arrival"
  state_topic: "polly/lastmsg"