###################################################
## Various MQTT sensors
###################################################

- platform: mqtt
  name: "polly_lastmsg"
  state_topic: "polly/lastmsg"