###################################################
## Various MQTT sensors
###################################################

- platform: mqtt
  state_topic: "polly/lastmsg"
  name: "polly_lastmsg"

- platform: mqtt
  state_topic: "ifttt/rachio/watering_time"
  name: "ifttt_rachio_watering_time"
