######################################################################
##  Announce when people come or go.
## Announce over all Chromecast Audios 
######################################################################
- alias: 'Announcements'
  
  hide_entity: True
  trigger:
    - platform: state
      entity_id:
        - device_tracker.carlo
        - device_tracker.stacey
        - device_tracker.franco
        - device_tracker.yolanda
        - device_tracker.joyce_ipad
        - cover.garadget_large
        - cover.garadget_small
       
  action:
    - service: script.Voice_notify
      data_template:
        message: "Attention.  {{ trigger.entity_id.split('.')[1].lower().replace('_ipad', '').title() }} is now {{ trigger.to_state.state }}"
        cache: true