###################################
##  Uses IFTTT to notify me of bad logins.
###################################

- alias: Login Failure
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sensor.badlogin
    above: 1
  action:
    service: ifttt.trigger
    data: {"event":"ifttt_notify", "value1":"Home Assistant Error: ", "value2":"Login Failure Detected"}
