###################################
##  Uses IFTTT to notify me of bad logins.
###################################

- alias: Login Failure
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sensor.badlogin
    above: 1

  action:
    service: script.ifttt_notify
    data_template:
      value1: 'Bad Login: '
      value2: 'There was a Hack attempt!'
      value3: ''
