######################################################################
##  Color Tornado!
######################################################################
- alias: 'Color Tornado'
  trigger:
    - platform: state
      entity_id: input_boolean.color_tornado
      state: 'on'
      from: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.justin_go
      data:
        effect: colorloop

    - service: input_boolean.turn_off
      entity_id: input_boolean.color_tornado
