######################################################################
##  Dark House Little extra light - DARK and Cloudy or just rainy.
######################################################################

- alias: 'Dark House Little extra light'  
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 20.0
    - platform: numeric_state
      entity_id: sensor.dark_sky_cloud_coverage
      above: 90
    - platform: numeric_state
      entity_id: sensor.dark_sky_precip_intensity
      above: 1
      
  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
          - condition: numeric_state
            entity_id: sun.sun
            value_template: '{{ state.attributes.elevation }}'
            below: 20.0
          - condition: numeric_state
            entity_id: sensor.dark_sky_cloud_coverage
            above: 90
      - condition: numeric_state
        entity_id: sensor.dark_sky_precip_intensity
        above: 1
            
  action:
    - service: light.turn_on
      entity_id: 
        - light.couch_1
      data:  
        transition: 1200 
    - service: switch.turn_on
      entity_id:
        - switch.living_room_outlet

######################################################################

######################################################################
##  Dark House Little extra light - RAIN is over.
######################################################################

- alias: 'Rain is over'  
  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_precip_intensity
      below: 1
      
  action:
    - service: light.turn_off
      entity_id: 
        - light.couch_1
      data:  
        transition: 1200 
    - service: switch.turn_off
      entity_id:
        - switch.living_room_outlet