###################################
##  Press an [Amazon Dash Buttons](http://amzn.to/2dPKZhM) and then stuff happens.
###################################

- alias: 'Toggle Office Light on/off'
  trigger:
    - platform: event
      event_type: brooklyn_dash

  action:
    # Disable this automation
    - service: automation.turn_off
      entity_id: dash_buttons.yaml
    - service: light.toggle
      entity_id: light.office_lamp
    - delay:
        minutes: 1
    # enable this automation - This prevents duplicate pushes.
    - service: automation.turn_on
