###################################
##  Press an [Amazon Dash Buttons](http://amzn.to/2dPKZhM) and then stuff happens.
###################################

- alias: 'Toggle Office Light on/off'
  trigger:
    - platform: event
      event_type: brooklyn_dash
    - platform: event
      event_type: simplehuman_dash
      
  action:
    - service: light.toggle
      entity_id: light.office_lamp
      
     
# - alias: 'Toggle Office Light off if on'
  # trigger:
    # - platform: event
      # event_type: brooklyn_dash

  # condition:
    # - condition: state
      # entity_id: light.office_lamp
      # state: 'on'
     
  # action:
    # - service: light.turn_off
      # entity_id: light.office_lamp
      