###################################
##  Press a dash Button and then stuff happens.
###################################

- alias: 'Toggle Office Light on if off'
  trigger:
    - platform: event
      event_type: brooklyn_dash

  condition:
    - condition: state
      entity_id: light.office_lamp
      state: 'off'
     
  action:
    - service: light.turn_on
      entity_id: light.office_lamp
      

- alias: 'Toggle Office Light off if on'
  trigger:
    - platform: event
      event_type: brooklyn_dash

  condition:
    - condition: state
      entity_id: light.office_lamp
      state: 'on'
     
  action:
    - service: light.turn_off
      entity_id: light.office_lamp
      