##############################################################################
###  Detect when things are on and forgotten about.
##############################################################################

- alias: Printer on for more than 35 minutes
  trigger:
    - platform: state
      entity_id: switch.printer_outlet
      state: 'on'
      for: '00:35:00'

#Turn it off twice for good measure!
  action:
    - service: switch.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"
    - delay: 00:01:00
    - service: switch.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"
 