###################################
##  Notifies me via IFTTT when something goes down.
###################################

- alias: 'Device Status'
  hide_entity: True
  trigger:
       - platform: state
         entity_id: 
           - sensor.wii
           - sensor.hue_hub
           - sensor.tablotv
           - sensor.alexa_echo
           - sensor.amazon_dot
           - sensor.circle
           - sensor.rachio
           - sensor.skybell
           #- sensor.samsungtv
           - sensor.chromecast_audio_1
           - sensor.chromecast_audio_2
           - sensor.nest_upstairs
           - sensor.nest_downstairs
           - sensor.ciscoap
           - sensor.actiontechap
           - sensor.garadget_small
           - sensor.garadget_large
  action:
    service: script.turn_on
    entity_id: script.notify_ifttt
    data_template:
      variables:
        value1: 'Device Status '
        value2: "{{ trigger.entity_id.split('.')[1] }} is "
        value3: "{{ trigger.to_state.state }}"
