######################################################################
##  Turn off my Office light whenever I leave the house.
######################################################################
- alias: 'Carlo has left the building'
  trigger:
    - platform: state
      entity_id: input_boolean.flash
      state: 'on'
      from: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - group.all_lights
      data:
        flash: long

    - service: input_boolean.turn_off
      entity_id: input_boolean.flash
