######################################################################
##  Good night Routine
######################################################################

- alias: 'Good Night Routine'
  trigger:
    - platform: event
      event_type: good_night
    - platform: state
      entity_id: 
        - sensor.samsungtv
        - sensor.withings_scale
      state: 'Offline'
      from: 'Online'

  condition:
    - condition: time
      after: '20:00:00'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
        
  action:
    - service: script.interior_off

      