# There is also an IFTTT recipe that shuts down all lights when Nest goes into Away mode. - event_type= Good_Night

- alias: 'GoodNight - Away Mode'
  trigger:
    - platform: event
      event_type: good_night
    - platform: state
      entity_id: binary_sensor.upstairs_away_mode
      to: 'on'
    - platform: state
      entity_id: binary_sensor.downstairs_away_mode
      to: 'on'  
    - platform: state
      entity_id: group.family
      state: not_home 

  condition:
    condition: state
    entity_id: group.family
    state: not_home 

  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: group.all_switches