######################################################################
##  Shut it all down.  No one is here or we went to sleep.
######################################################################

- alias: 'GoodNight - Away Mode'
  trigger:
    - platform: event
      event_type: good_night
    - platform: state
      entity_id: binary_sensor.upstairs_away_mode
      to: 'on'
    - platform: state
      entity_id: binary_sensor.downstairs_away_mode
      to: 'on'  
    - platform: state
      entity_id: group.family
      state: not_home 

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: not_home 
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'

  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: group.amps