######################################################################
##  Good night Routine
######################################################################

- alias: 'Good Morning Routine'
  trigger:
    - platform: event
      event_type: good_night

  condition:
    - condition: state
      entity_id: group.family
      state: home 
        
  action:
    - service: light.turn_off
      entity_id: 
        - group.interior_lights
        
        
      