######################################################################
##  Good night Routine
######################################################################

- alias: 'Good Night Routine'
  trigger:
    - platform: event
      event_type: good_night

  # condition:
    # - condition: state
      # entity_id: group.family
      # state: home 
        
  action:
    - service: script.interior_off

      