###################################
##  Flash the lights on Halloween for the Tricker Treaters!
###################################
- alias: 'halloween flasher'
  trigger:
    - platform: sun
      event: sunset
    - platform: event
      event_type: skybell_motion_disabled_until_next_year

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: time
        before: '23:45'

  action:
    - service: light.turn_on
      entity_id: group.halloween_flasher
      data:
        flash: long
    - delay: 00:00:2
    - service: light.turn_on
      entity_id: group.halloween_flasher
      data:
        flash: long
    - delay: 00:00:2
    - service: light.turn_on
      entity_id: group.halloween_flasher
      data:
        flash: long
    - delay: 00:00:3
    - service: light.turn_on
      entity_id: group.halloween_flasher
      data:
        flash: long
    - delay: 00:00:5
    - service: light.turn_on
      entity_id: group.halloween_flasher
      data:
        flash: long