###################################
##  Holiday Lights on/off with IFTTT/Alexa support
###################################

- alias: 'Holiday Stuff on'  
  trigger:
    - platform: sun
      event: sunset
    - platform: event
      event_type: holiday_lights_on
              
  action:
   - service: script.holiday_switches_on
    
    
- alias: 'Holiday Stuff off'  
  trigger:
    - platform: sun
      event: sunrise
      offset: '-0{{ (range(1, 3)|random|int) }}:{{ (range(1, 59)|random|int) }}:00'
    - platform: event
      event_type: holiday_lights_off          

  action:
    - service: script.switch_turn_off_all

      