###################################
##  Holiday Lights on/off with IFTTT/Alexa support
###################################

- alias: 'Holiday Stuff on'  
  trigger:
    - platform: sun
      event: sunset
    - platform: event
      event_type: holiday_lights_on
              
  action:
    - service: switch.turn_on
      entity_id: switch.den_outlet
    - delay: 00:00:30
    - service: switch.turn_on
      entity_id: switch.living_room_outlet
    - service: switch.turn_on
      entity_id: switch.dining_room_outlet
    - delay: 00:00:30
    
- alias: 'Holiday Stuff off'  
  trigger:
    - platform: sun
      event: sunrise
      offset: '-03:30:00'
    - platform: event
      event_type: holiday_lights_off          

  action:
    - service: script.switch_turn_off_all

      