###################################
##  Holiday Lights on/off with IFTTT/Alexa support
###################################

- alias: 'Holiday Stuff on'  
  trigger:
    - platform: sun
      event: sunset
    - platform: event
      event_type: halloween_lights_on
              
  action:
    - service: switch.turn_on
      entity_id: switch.outlet_den
    - delay: 00:00:30
    - service: switch.turn_on
      entity_id: switch.outlet_living_room
    
- alias: 'Holiday Stuff off'  
  trigger:
    - platform: sun
      event: sunrise
      offset: '-03:30:00'
    - platform: event
      event_type: halloween_lights_off          

  action:
    - service: switch.turn_off
      entity_id: switch.outlet_den
    - delay: 00:00:30
    - service: switch.turn_off
      entity_id: switch.outlet_living_room

      