###################################
##  Turn on/off Living Room AMPs via ALexa/IFTTT event.
## Currently using this [AMP] (http://amzn.to/2joRrk1)
## [Etekcity Outlets](http://amzn.to/2efNoBP)
## [433Mhz Transmitter and receiver](http://amzn.to/2dceNY2)
###################################

- alias: 'IFTTT Turn AMP on'
  trigger:
    - platform: event
      event_type: amp_on
    - platform: state
      entity_id: media_player.whole_house
      from: 'off'
      to: 'playing'
    - platform: state
      entity_id: media_player.livingroomcc
      from: 'off'
      to: 'playing'
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_amp
      
      
- alias: 'IFTTT Turn AMP off'
  trigger:
    - platform: event
      event_type: amp_off
    - platform: state
      entity_id: media_player.whole_house
      from: 'playing'
      to: 'off'
    - platform: state
      entity_id: media_player.livingroomcc
      from: 'playing'
      to: 'off'
      
  action:
    - service: switch.turn_off
      entity_id: switch.living_room_amp
      
