###################################
##  Turn on/off Printer via ALexa/IFTTT event.  Turn off automatically after 20 minutes
###################################

- alias: 'IFTTT Turn Printer on'
  trigger:
    - platform: event
      event_type: printer_on

  action:
    - service: switch.turn_on
      entity_id: switch.printer_outlet
    - delay: 00:20:00
    - service: switch.turn_off
      entity_id: switch.printer_outlet
           
      
- alias: 'IFTTT Turn Printer off'
  trigger:
    - platform: event
      event_type: printer_off

  action:
    - service: switch.turn_off
      entity_id: switch.printer_outlet
      
