###################################
##  Turn on/off Living Room AMPs via ALexa/IFTTT event.
###################################

- alias: 'IFTTT Turn AMP on'
  trigger:
    - platform: event
      event_type: amp_on

  action:
    - service: switch.turn_on
      entity_id: switch.living_room_amp
      
      
- alias: 'IFTTT Turn AMP off'
  trigger:
    - platform: event
      event_type: amp_off

  action:
    - service: switch.turn_off
      entity_id: switch.living_room_amp
      
