###################################
##  LOG IFTTT Stuff - SkyBell
###################################

- alias: 'Log SkyBell Pressed Activity'
  hide_entity: True
  trigger:
    - platform: event
      event_type: skybell_pressed
  
  action:
    - service: logbook.log
      data:
        name: "SkyBell HD Doorbell:"
        message: "Someone Pressed the Doorbell."
  
######################################################################

- alias: 'Log SkyBell Motion detection'
  hide_entity: True
  trigger:
    - platform: event
      event_type: skybell_motion
  
  action:
    - service: script.front_house_motion
