###################################
##  Late Night lights Section
###################################
- alias: 'Late Night Helper'
  trigger:
    - platform: state
      entity_id: binary_sensor.upstairs_away_mode
      state: 'off'
    - platform: state
      entity_id: binary_sensor.downstairs_away_mode
      state: 'off'  
    - platform: state
      entity_id: group.family
      state: home 
    - platform: state
      entity_id: group.garage_doors
      state: 'open'
      for: '00:01:30'
    
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: time
        after: '20:00:00'
        before: '02:00:00'

  action:
    - service: light.turn_on
      entity_id: 
        - group.living_room_accents
        - light.living_room_slider
        - light.foyer_door
        - light.fridge
        - light.M1_front_right
        - light.S1
        - light.S4
      data:
        brightness: 150
    - service: switch.turn_on
      entity_id: switch.kitchen_accents
    - delay: '00:00:30'
    - service: switch.turn_on
      entity_id: switch.living_room_outlet
    - delay: '00:00:30'
    - service: switch.turn_on
      entity_id: switch.foyer_outlet
    - delay: '00:08:00'
    - service: light.turn_off
      entity_id: 
        - light.S1
        - light.S4
        - light.foyer_door
        - light.fridge
        
  
