###################################
##  Late Night lights Section
###################################
- alias: 'Late Night Helper'
  trigger:
    - platform: state
      entity_id: binary_sensor.upstairs_away_mode
      state: 'off'
    - platform: state
      entity_id: binary_sensor.downstairs_away_mode
      state: 'off'  
    - platform: state
      entity_id: group.family
      state: home 

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: time
        after: '20:00'
        before: '02:00'

  action:
    service: light.turn_on
    entity_id: 
      - group.living_room_accents
      - light.living_room_slider
      - light.foyer_door
      - light.fridge
      - light.sink
      - light.M1_front_right
    data:
      brightness: 150
  
