###################################
##  Late Night lights Section
###################################
- alias: 'Late Night Helper'
  trigger:
    - platform: state
      entity_id: binary_sensor.upstairs_away_mode
      state: 'off'
    - platform: state
      entity_id: binary_sensor.downstairs_away_mode
      state: 'off'  
    - platform: state
      entity_id: group.family
      state: home 

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: time
        before: '23:45'

  action:
    service: light.turn_on
    entity_id: 
      - group.living_room_accents
      - light.living_room_slider
      - light.foyer_door_light
      - light.kitchen_fridge_light
      - light.kitchen_sink_light
      - light.living_room_front_right
    data:
      brightness: 200
  
