# Here is a collection of automations for logging IFTTT supported devices in LogBook.

- alias: 'Log Sprinkler Activity'
  trigger:
    - platform: event
      event_type: rachio_water_stops
  
  action:
    service: logbook.log
    data:
      name: "Rachio Sprinkler:"
      message: "The Lawn was watered just now."
