###################################
##  Start Up Section
###################################

- alias: Startup Notification and Shut startup lights
  hide_entity: True
  trigger:
    - platform: event
      event_type: homeassistant_start
  action:
    - service: script.ifttt_notify
      data_template:
        value1: 'Startup: Home Assistant is Up and Running!'
        value2: ''
        value3: ''

    - service: script.Voice_notify
      data:
        value1: 'Home Assistant is now online and running.'
        
    - service: light.turn_off
      entity_id: group.hallway_lights
    