###################################
##  Start Up Section
###################################

- alias: Startup Notification
  hide_entity: True
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
    service: script.turn_on
    entity_id: script.notify_ifttt
    data_template:
      variables:
        value1: "Startup: Home Assistant is Up and Running!"
        value2: ""
        value3: ""
