###################################
##  Sunrise and Sunset stuff
###################################

- alias: 'Sunset Stuff on'  
  trigger:
    - platform: sun
      event: sunset
#    - platform: event
#      event_type: halloween_lights_on
              
  action:
    - service: switch.turn_on
      entity_id: switch.foyer_outlet 
    - service: light.turn_on
      entity_id: light.pool_bathroom
    - service: light.turn_on
      data:
        entity_id: light.outdoor_foyer
        brightness: 200
        rgb_color: [61,178,112]
        
- alias: 'Sunset Stuff off'  
  trigger:
    - platform: sun
      event: sunrise
      offset: '-03:30:00'
#    - platform: event
#      event_type: halloween_lights_off          

  action:
    - service: switch.turn_off
      entity_id: switch.foyer_outlet
    - service: light.turn_off
      entity_id: light.outdoor_foyer
    - service: light.turn_off
      entity_id: light.pool_bathroom  
    - service: light.turn_off
      entity_id: group.outdoor_lights      