      ###################################
##  Sunrise and Sunset stuff
###################################

- alias: 'Sunset Stuff on'  
  trigger:
    - platform: sun
      event: sunset
              
  action:
    - service: script.monthly_front_house_scene
    - service: script.holiday_switches_on
    - service: light.turn_on
      entity_id: 
        - light.outdoor_bathroom
        - light.tv_light
        - light.tv_stand_light
      data:  
        transition: 1200 
    
######################################################################

- alias: 'Sunset Stuff off'  
  trigger:
    - platform: sun
      event: sunrise
      offset: '-03:25:00'       

  action:
    - service: light.turn_off
      entity_id: group.all_lights    
    - service: script.interior_off
    - delay: '00:01:00'
    - service: script.switch_turn_off_all
    
      
    
     