###################################
##  Sunrise and Sunset stuff
###################################

- alias: 'Sunset Stuff on'  
  trigger:
    - platform: sun
      event: sunset
              
  action:
    - service: script.monthly_front_house_scene
    - service: switch.turn_on
      entity_id: switch.living_room_outlet 
    - delay: '00:00:30'
    - service: switch.turn_on
      entity_id: switch.den_outlet
    - delay: '00:00:30'
    - service: switch.turn_on
      entity_id: switch.living_room_outlet 
    - delay: '00:00:30'
    - service: switch.turn_on
      entity_id: switch.foyer_outlet 
    - service: light.turn_on
      entity_id: light.outdoor_bathroom
       
    
######################################################################

- alias: 'Sunset Stuff off'  
  trigger:
    - platform: sun
      event: sunrise
      offset: '-03:30:00'       

  action:
    - service: light.turn_off
      entity_id: group.all_lights    
    - service: script.switch_turn_off_all
    
      
    
     