###################################
##  Holiday Lights on/off with IFTTT/Alexa support
###################################

- alias: 'Sunset Stuff on'  
  trigger:
    - platform: sun
      event: sunset
#    - platform: event
#      event_type: halloween_lights_on
              
  action:
    - service: switch.turn_on
      entity_id: switch.foyer_outlet 
    
- alias: 'Sunset Stuff off'  
  trigger:
    - platform: sun
      event: sunrise
      offset: '-03:30:00'
#    - platform: event
#      event_type: halloween_lights_off          

  action:
    - service: switch.turn_off
      entity_id: switch.foyer_outlet
      