- alias: detect_light_between 8am and 8pm
  trigger:
    - platform: event
      event_type: state_changed
  condition:
    - condition: state
      entity_id: group.family
      state: home 
    - condition: time
      after: '08:00:00'
    - condition: time
      before: '20:00:00'
    - condition: template
      value_template: "{{ trigger.event.data.entity_id.split('.')[1] != 'tv_light' }}"
    - condition: template
      value_template: "{{ trigger.event.data.entity_id.split('.')[1] != 'tv_stand_light' }}"
    - condition: template
      value_template: "{{ trigger.event.data.entity_id.split('.')[0] == 'light' }}"
    - condition: template
      value_template: "{{ trigger.event.data.new_state.state == 'on' }}"
    - condition: template
      value_template: "{{ trigger.event.data.old_state.state == 'off' }}"
  action:
    - service: light.turn_on
      data_template:
        entity_id: "{{ trigger.event.data.entity_id }}"
        brightness: 255