- alias: detect_light_between 5am and 8am
  trigger:
    - platform: event
      event_type: state_changed
  condition:
    - condition: state
      entity_id: group.family
      state: home 
    - condition: time
      after: '05:00:00'
    - condition: time
      before: '7:59:00'
    - condition: template
      value_template: "{{ trigger.event.data.entity_id.split('.')[0] == 'light' }}"
    - condition: template
      value_template: "{{ trigger.event.data.entity_id.split('_')[0] != 'light.tv' }}"
    - condition: template
      value_template: "{{ trigger.event.data.entity_id.split('_')[0] != 'light.couch' }}"
    - condition: template
      value_template: "{{ trigger.event.data.entity_id.split('_')[0] != 'light.outdoor' }}"
    - condition: template
      value_template: "{{ trigger.event.data.new_state.state == 'on' }}"
    - condition: template
      value_template: "{{ trigger.event.data.old_state.state == 'off' }}"
#    - condition: template
#      value_template: "{{ trigger.event.data.new_state.attributes.brightness|default(0)|int > 50 }}"
  action:
    - service: light.turn_on
      data_template:
        entity_id: "{{ trigger.event.data.entity_id }}"
        brightness: 50