- alias: TV Time    
  trigger:
    - platform: sun
      event: sunset
      offset: '+00:30:00'
    - platform: event
      event_type: tv_time
    - platform: state
      entity_id: sensor.samsungtv
      state: Online
      
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: home
      - condition: state
        entity_id: sensor.samsungtv
        state: Online
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition:
        platform: state
        entity_id: input_boolean.guest_mode
        state: 'off'
        
  action:
    service: scene.turn_on
    entity_id: scene.living_room_tv_time
