- alias: "Update Available Notification"
  hide_entity: True
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: ifttt.trigger
    data: {"event":"device_status", "value1":"Home Assistant Update: ", "value2":"Available"}
 