# Uses the Nest thermostat to turn on lights and turn them off.

- alias: 'Upstairs Light Turn on'
  trigger:
    - platform: event
      event_type: upstairs_light_on
  
  condition:
      condition: state
      entity_id: sun.sun
      state: 'below_horizon'

  action:
    service: light.turn_on
    entity_id: group.upstairs

- alias: 'Upstairs Light Turn off'
  trigger:
    - platform: event
      event_type: upstairs_light_off
  
  action:
    service: light.turn_off
    entity_id: group.upstairs