##############################################################################
###  Detect when things are on and forgotten about.
##############################################################################

- alias: Automated Switch WatchDog!
  trigger:
    - platform: state
      entity_id: switch.printer_outlet
      state: 'on'
      for: '00:35:00'
    - platform: state
      entity_id: switch.garage_outlet
      state: 'on'
      for: '03:00:00'
      
#Turn it off twice for good measure!
  action:
    - service: switch.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"
    - delay: 00:01:00
    - service: switch.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"
 
 ##############################################################################
 
- alias: Automated Light WatchDog!
  trigger:
    - platform: state
      entity_id: light.hallway
      state: 'on'
      for: '00:20:00'
      
#Turn it off!
  action:
    - service: light.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"
