##############################################################################
###  Detect when things are on and forgotten about.
##############################################################################

- alias: Automated Switch WatchDog!
  trigger:
    - platform: state
      entity_id: switch.printer_outlet
      state: 'on'
      for: '00:35:00'
    - platform: state
      entity_id: switch.garage_outlet
      state: 'on'
      for: '03:00:00'
      
#Turn it off twice for good measure!
  action:
    - service: switch.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"
    - delay: 00:01:00
    - service: switch.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"
 
 ##############################################################################
 
- alias: Automated Light WatchDog!
  trigger:
    - platform: state
      entity_id: light.hallway
      state: 'on'
      for: '00:20:00'
    - platform: state
      entity_id: group.foyer_lights
      state: 'on'
      for: '00:20:00'
      
#Turn it off!
  action:
    - service: light.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"

##############################################################################

- alias: If Outdoor lights are on and it's daytime, TURN THEM OFF!!
  hide_entity: True
  trigger:
    - platform: time
      minutes: '/47'
      seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: group.outdoor_lights
      state: 'on'
      
  action:
    - service: light.turn_off
      entity_id: group.outdoor_lights

##############################################################################

# - alias: Add some double and triple checking to the 433 RF outlets.
  # hide_entity: True
  # trigger:
    # - platform: time
      # minutes: 43
      # seconds: 0
      
  # action:
    # - service: script.reliability

##############################################################################

- alias: "NOTIFY IF IP CHANGES"
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.ipchange
      from: 'False'
      to: 'True'
  action:
    - service: script.ifttt_notify
      data_template:
        value1: 'Changed IP address:'
        value2: "New IP: {{ states('sensor.exteral_ip') }}"
        value3: ' - Be sure to Change DNS!'

##############################################################################


