##############################################################################
###  Detect when things are on and forgotten about. Like any Good Watchdog.
##############################################################################

- alias: Automated Switch WatchDog!
  trigger:
    - platform: state
      entity_id: switch.printer_outlet
      state: 'on'
      for: '00:20:00'
    - platform: state
      entity_id: switch.garage_outlet
      state: 'on'
      for: '03:00:00'
      
#Turn it off twice for good measure!
  action:
    - service: switch.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"
    - delay: 00:01:00
    - service: switch.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"
 
 ##############################################################################
 
- alias: Automated Light WatchDog!
  trigger:
    - platform: state
      entity_id: 
        - light.hallway
        - group.foyer_lights
        - light.master_toilet
      state: 'on'
      for: '00:20:00'

    - platform: state
      entity_id:
        - light.paige_go
        - light.justin_go
        - group.upstairs
      state: 'on'
      for: '02:00:00'
      
#Turn it off!
  action:
    - service: light.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"

##############################################################################

- alias: "NOTIFY IF IP CHANGES"
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.ipchange
      from: 'False'
      to: 'True'
  action:
    - service: script.ifttt_notify
      data_template:
        value1: 'Changed IP address:'
        value2: "New IP: {{ states('sensor.exteral_ip') }}"
        value3: ' - Be sure to Change DNS!'

##############################################################################

- alias: "New device connected"
  trigger:
    - platform: event
      event_type: device_tracker_new_device
  action:
    - service: script.Voice_notify
      data_template:
        value1: "There has been a new device detected on the network.  Be sure to appropriately catagorie it within Circle."
