######################################################################
##  Time to work - Set it up!
######################################################################

- alias: Time to Work   
  trigger:
    - platform: event
      event_type: work
        
  action:
    - service: light.turn_off
      entity_id: 
        - group.dinette
        - group.kitchen
        - group.living_room
    - service: light.turn_on
      entity_id: 
        - light.office_lamp
