###################################
##  ZWave Section -
##  Home Assistant runs on my [Raspberry Pi 3](http://amzn.to/2e3DOBY) with [Aeon Labs Z Wave Stick (GEN 5)](http://amzn.to/2eAiAP0).
###################################

##############################################################
- alias: Hallway ZWave Enerwave Door Sensors Open
  hide_entity: True
  trigger:
    - platform: event
      event_type: zwave.node_event
      event_data:
        object_id: enerwave_unknown_type0601_id0903_2
        basic_level: 255
    - platform: state
      entity_id: binary_sensor.aeotec_dsb04100_doorwindow_sensor_sensor_4_0
      to: 'on'

  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-03:00:00'
      - condition: numeric_state
        entity_id: sensor.dark_sky_cloud_coverage
        above: 50

  action:
    - service: light.turn_on
      entity_id:
        - light.kids_hallway
        - light.k4
    - delay: 00:20:00
    - service: light.turn_off
      entity_id: light.kids_hallway

##############################################################
- alias: ZWave Enerwave Door Sensors Closed
  hide_entity: True
  trigger:
    - platform: event
      event_type: zwave.node_event
      event_data:
        object_id: enerwave_unknown_type0601_id0903_2
        basic_level: 0
    - platform: state
      entity_id: binary_sensor.aeotec_dsb04100_doorwindow_sensor_sensor_4_0
      state: 'off'

  action:
    service: light.turn_off
    entity_id: light.kids_hallway

##############################################################
- alias: Shutdown Helper light
  hide_entity: True
  trigger:
    - platform: state
      entity_id: light.k4
      state: 'on'
      for: '00:20:00'
    - platform: event
      event_type: zwave.node_event
      event_data:
       object_id: enerwave_unknown_type0601_id0903_2
       basic_level: 0
    - platform: state
      entity_id: binary_sensor.aeotec_dsb04100_doorwindow_sensor_sensor_4_0
      state: 'off'

  condition:
    condition: state
    entity_id: light.k1
    state: 'off'

  action:
    - service: light.turn_off
      entity_id: light.k4
