#-------------------------------------------
#  ALarm Related Packages
#-------------------------------------------
homeassistant:
  customize:
    device_tracker.NodeMCU1:
      icon: mdi:chip
      emulated_hue: False
      hidden: True
    device_tracker.NodeMCU2:
      icon: mdi:chip
      emulated_hue: False
      hidden: True
    binary_sensor.MCU1_GPIO12:
      friendly_name: 'Interior Garage Door'
      emulated_hue: False
      hidden: false
    binary_sensor.MCU1_GPIO14:
      friendly_name: 'Office Window'
      emulated_hue: False
      hidden: false
    binary_sensor.MCU1_GPIO4:
      friendly_name: 'Paige Window'
      emulated_hue: False
      hidden: false
    binary_sensor.MCU1_GPIO10:
      friendly_name: 'Dining Room Windows'
      emulated_hue: False
      hidden: false
    binary_sensor.MCU1_GPIO0:
      friendly_name: 'Front Den Windows'
      emulated_hue: False
      hidden: false
    binary_sensor.MCU1_GPIO2:
      friendly_name: 'GPIO2'
      emulated_hue: False
      hidden: false
    binary_sensor.MCU1_GPIO5:
      friendly_name: 'Front Door'
      emulated_hue: False
      hidden: false
#-------------------------------------------
binary_sensor:
  - platform: mqtt
    state_topic: "NodeMCU1/GPIO12/Status"
    name: "MCU1_GPIO12"
    payload_on: 1
    payload_off: 0
    device_class: opening
  - platform: mqtt
    state_topic: "NodeMCU1/GPIO14/Status"
    name: "MCU1_GPIO14"
    payload_on: 1
    payload_off: 0
    device_class: opening
  - platform: mqtt
    state_topic: "NodeMCU1/GPIO10/Status"
    name: "MCU1_GPIO10"
    payload_on: 1
    payload_off: 0
    device_class: opening
  - platform: mqtt
    state_topic: "NodeMCU1/GPIO0/Status"
    name: "MCU1_GPIO0"
    payload_on: 1
    payload_off: 0
    device_class: opening
  - platform: mqtt
    state_topic: "NodeMCU1/GPIO2/Status"
    name: "MCU1_GPIO2"
    payload_on: 1
    payload_off: 0
    device_class: opening
  - platform: mqtt
    state_topic: "NodeMCU1/GPIO4/Status"
    name: "MCU1_GPIO4"
    payload_on: 1
    payload_off: 0
    device_class: opening
  - platform: mqtt
    state_topic: "NodeMCU1/GPIO5/Status"
    name: "MCU1_GPIO5"
    payload_on: 1
    payload_off: 0
    device_class: opening
#-------------------------------------------
sensor:
  - platform: template
    sensors:
      nodemcu1:
        friendly_name: 'NodeMCU1'
        value_template: "{{ 'Online' if is_state('device_tracker.NodeMCU1', 'home') else 'Offline' }}"

#-------------------------------------------
group:
  entry_points:
    entities:
      - binary_sensor.MCU1_GPIO0
      - binary_sensor.MCU1_GPIO2
      - binary_sensor.MCU1_GPIO4
      - binary_sensor.MCU1_GPIO5
      - binary_sensor.MCU1_GPIO10
      - binary_sensor.MCU1_GPIO12
      - binary_sensor.MCU1_GPIO14
