#-------------------------------------------
#  ALarm Related Packages
#-------------------------------------------
homeassistant:
  customize:
    binary_sensor.door1:
      friendly_name: Interior Garage Door
      emulated_hue: False
      hidden: False
    device_tracker.NodeMCU1:
      icon: mdi:chip
      emulated_hue: False
      hidden: True
#-------------------------------------------
binary_sensor:
  - platform: mqtt
    state_topic: "NodeMCU1/Door1/Status"
    name: "Door1"
    payload_on: 1
    payload_off: 0
    device_class: opening
  - platform: mqtt
    state_topic: "NodeMCU1/Door2/Status"
    name: "Door2"
    payload_on: 1
    payload_off: 0
    device_class: opening
  - platform: mqtt
    state_topic: "NodeMCU1/Door3/Status"
    name: "Door3"
    payload_on: 1
    payload_off: 0
    device_class: opening
  - platform: mqtt
    state_topic: "NodeMCU1/Door4/Status"
    name: "Door4"
    payload_on: 1
    payload_off: 0
    device_class: opening

  - platform: mqtt
    state_topic: "NodeMCU1/Door6/Status"
    name: "Door6"
    payload_on: 1
    payload_off: 0
    device_class: opening
  - platform: mqtt
    state_topic: "NodeMCU1/Door7/Status"
    name: "Door7"
    payload_on: 1
    payload_off: 0
    device_class: opening
#-------------------------------------------
sensor:
  - platform: template
    sensors:
      nodemcu1:
        friendly_name: 'NodeMCU1'
        value_template: "{{ 'Online' if is_state('device_tracker.NodeMCU1', 'home') else 'Offline' }}"

#-------------------------------------------
group:
  entry_points:
    entities:
      - binary_sensor.door1
      - binary_sensor.Door2
      - binary_sensor.Door3
      - binary_sensor.Door4
      - binary_sensor.Door6
      - binary_sensor.Door7
