#-------------------------------------------
#  Space Related Packages
#-------------------------------------------

#-------------------------------------------
sensor:
  - platform: mqtt
    state_topic: "NodeMCU1/Door1/status"
    name: "Door1"
  - platform: mqtt
    state_topic: "NodeMCU1/Door2/status"
    name: "Door2"
  - platform: mqtt
    state_topic: "NodeMCU1/Door3/status"
    name: "Door3"
  - platform: mqtt
    state_topic: "NodeMCU1/Door4/status"
    name: "Door4"
  - platform: mqtt
    state_topic: "NodeMCU1/Door5/status"
    name: "Door5"
  - platform: mqtt
    state_topic: "NodeMCU1/Door6/status"
    name: "Door6"
  - platform: mqtt
    state_topic: "NodeMCU1/Door7/status"
    name: "Door7"
#-------------------------------------------
