#-------------------------------------------
#  Package to make sure all automations are Autostarted.
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------
homeassistant:
  customize_glob:
    - "automation.*watchdog*":
        icon: mdi:timer
    - "sensor.dark_sky_*":
        homebridge_hidden: true
    - "scene.month_*_colors":
        hidden: true
        emulated_hue: false
        homebridge_hidden: true

  customize_domain:
    - automation:
       initial_state: 'on'
