#-------------------------------------------
#  Package to make sure all automations are Autostarted.
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------
homeassistant:
  customize_domain:
    automation:
      initial_state: 'on'
  customize:
    group.all_automations:
      control: show
