#-------------------------------------------
#  RSS Podcast Alerting function Packages
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
feedreader:
    urls:
      - https://hasspodcast.io/feed/podcast
#-------------------------------------------

automation:
  - alias: Send notification of RSS feed title when updated
    trigger:
      platform: event
      event_type: feedreader

    action:
      - service: script.ifttt_notify
        data_template:
          value1: 'There is a new HA Podcast available!'
          value2: "{{ trigger.event.data.title }}"
          value3: "{{ trigger.event.data.link }}" 

      - service: notify.html5
        data_template:
          title: "New HA Podcast available"
          message: "{{ trigger.event.data.title }} - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          data:
            url: "{{ trigger.event.data.link }}"

      - service: persistent_notification.create
        data:
          title: "New HA Podcast available"
          message: "{{ trigger.event.data.title }} - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          notification_id: "update_available"
