      ###################################
##  Sunrise and Sunset stuff
###################################

- alias: 'Sunset Stuff off'
  trigger:
    - platform: sun
      event: sunrise
      offset: '-01:30:00'

  action:
    - service: light.turn_off
      entity_id:
        - group.exterior_lights
        - group.outdoor_front_lights
        - group.outdoor_pool_lights
        - group.all_lights
    - service: script.interior_off
